In [1]:
import auxfunctions as aux
import pandas as pd
import tabula

# ResultList_25

In [3]:
ResultList_25 = "pdfs/ResultList_25.pdf"
tabu = tabula.read_pdf(ResultList_25, pages='all')
tabu = tabu[0]
gender, distance, style, category, date, time = aux.gender_distance_style_category_date_time(tabu)
tabu2727 = aux.add_columns(tabu, gender=gender, distance=distance, style=style, category=category, date_string=date, time_string=time) #add_columns has dataframe as input
print(tabu.head(5))

                     Prueba 25                Masc., 200m Estilos Unnamed: 0  \
0           04/11/2023 - 16:15                                NaN        NaN
1                Clasificación                                 AN        NaN
2  1. RODRIGUEZ CASTRO, Victor      11 C.D.N. Ciudad De Algeciras        NaN
3       50m: 36.09 36.09 100m:  1:16.40 40.31 150m: 2:04.16 47.76      200m:
4      2. MOLINA NUÑEZ, Victor               11 C.N. San Fernando        NaN

  Unnamed: 1 Alevín Masc. gender distance    style category       date  \
0        NaN   Resultados   masc      200  estilos   alevin 2023-11-04
1     Tiempo       Puntos   masc      200  estilos   alevin 2023-11-04
2    2:41.21            -   masc      200  estilos   alevin 2023-11-04
3    2:41.21        37.05   masc      200  estilos   alevin 2023-11-04
4    2:58.52            -   masc      200  estilos   alevin 2023-11-04

       time
0  16:15:00
1  16:15:00
2  16:15:00
3  16:15:00
4  16:15:00

In [4]:
ResultList_26 = "pdfs/ResultList_26.pdf"

In [5]:
tabu = tabula.read_pdf(ResultList_26, pages='all')
tabu = tabu[0]
gender, distance, style, category, date, time = aux.gender_distance_style_category_date_time(tabu)
tabu = aux.add_columns(tabu, gender=gender, distance=distance, style=style, category=category, date_string=date, time_string=time) #add_columns has dataframe as input
print(tabu.head(5))

                   Prueba 26                 Fem., 200m Estilos  Unnamed: 0  \
0         04/11/2023 - 16:20                                NaN         NaN
1              Clasificación                                 AN         NaN
2  1. ESCOBAR CHERBUY, Clara                11 C.N. Los Barrios         NaN
3     50m: 32.25 32.25 100m:  1:09.95 37.70 150m: 1:58.47 48.52         NaN
4    2. MENA OROZCO, Carlota                 11 C.D.N. Sanlucar         NaN

  Unnamed: 1 Unnamed: 2 Alevín Fem. gender distance    style category  \
0        NaN        NaN  Resultados    fem      200  estilos   alevin
1        NaN     Tiempo      Puntos    fem      200  estilos   alevin
2        NaN    2:36.46           -    fem      200  estilos   alevin
3      200m:    2:36.46       37.99    fem      200  estilos   alevin
4        NaN    2:40.31           -    fem      200  estilos   alevin

        date      time
0 2023-11-04  16:20:00
1 2023-11-04  16:20:00
2 2023-11-04  16:20:00
3 2023-11-04  16:20:00
4 2023-11-04  16:20:00

In [52]:
tabula.read_pdf("pdfs/ResultList_39.ptabu", pages='all', multiple_tables=False)[0]

,Prueba 39,Unnamed: 1,"Fem., 100m Espalda",Unnamed: 3,Alevín Fem.
0,04/11/2023 - 18:13,NaN,NaN,NaN,Resultados
1,Clasificación,NaN,AN,Tiempo,Puntos
2,"1. RUZ ALCAIDE, Virginia",NaN,11 Club Natacion Jerez,1:09.37,-
3,50m: 34.01 34.01 100m:,NaN,1:09.37 35.36,NaN,NaN
4,"2. RAMOS ROMERO, Alma",NaN,11 C.D.N. Sanlucar,1:17.14,-
5,50m: 37.02 37.02 100m:,NaN,1:17.14 40.12,NaN,NaN
6,"3. MORENO BUSTOS, Claudia",NaN,11 C.D.N. Ciudad De Algeciras,1:19.40,-
7,50m: 38.40 38.40 100m:,NaN,1:19.40 41.00,NaN,NaN
8,"4. REYES GARCÍA, Álex",NaN,12 Club Natacion Jerez,1:27.42,-
9,50m: 42.80 42.80 100m:,NaN,1:27.42 44.62,NaN,NaN
10,"5. MONGE AIXELA, Valeria",NaN,12 C.D.N. Ciudad De Algeciras,1:28.34,-
11,50m: 43.24 43.24 100m:,NaN,1:28.34 45.10,NaN,NaN
12,"6. ESTEVEZ TERROBA, Leire",NaN,12 C.N. San Fernando,1:29.16,-
13,50m: 43.53 43.53 100m:,NaN,1:29.16 45.63,NaN,NaN
14,"7. LÓPEZ MONTAÑO, María",NaN,12 C.D.N. Sanlucar,1:29.34,-
15,50m: 43.64 43.64 100m:,NaN,1:29.34 45.70,NaN,NaN
16,"8. MARTIN MORALES, Adriana",NaN,11 Club Natacion Jerez,1:30.89,-
17,50m: 44.43 44.43 100m:,NaN,1:30.89 46.46,NaN,NaN
18,"9. MENJIBAR FANDIÑO, Carolina",NaN,11 C.N. Bahia De Cadiz,1:32.08,-
19,50m: 43.72 43.72 100m:,NaN,1:32.08 48.36,NaN,NaN
20,"10. JIMENEZ MARTINEZ, Claudia",NaN,12 C.N. San Fernando,1:32.91,-
21,50m: 45.51 45.51 100m:,NaN,1:32.91 47.40,NaN,NaN
22,"11. JIMENEZ RUBIO, Lola",NaN,12 C.N. Los Barrios,1:33.04,-
23,50m: 45.94 45.94 100m:,NaN,1:33.04 47.10,NaN,NaN
24,"12. VERDEJO JAEN, Elena",NaN,12 C.N. Los Barrios,1:33.86,-
25,50m: 46.18 46.18 100m:,NaN,1:33.86 47.68,NaN,NaN
26,"13. BUZON SERRANO, Genoveva",NaN,12 C.D.N. Sanlucar,1:34.61,-
27,50m: 45.75 45.75 100m:,NaN,1:34.61 48.86,NaN,NaN
28,"14. ANTÚNEZ RUIZ, Elena",NaN,11 C.N. Los Barrios,1:35.20,-
29,50m: 46.43 46.43 100m:,NaN,1:35.20 48.77,NaN,NaN
30,"15. PRECIADO VAZQUEZ, Valeria",NaN,12 C.N. Los Barrios,1:37.02,-
31,50m: 46.44 46.44 100m:,NaN,1:37.02 50.58,NaN,NaN
32,"16. ALI MARQUEZ, Maryam",NaN,12 C.D.N. Ciudad De Algeciras,1:37.46,-
33,50m: 48.07 48.07 100m:,NaN,1:37.46 49.39,NaN,NaN
34,"17. BRAZA RAMOS, Julia",NaN,12 C.D.N. Sanlucar,1:37.57,-
35,50m: 46.25 46.25 100m:,NaN,1:37.57 51.32,NaN,NaN
36,"18. CARO VEGA, Marta",NaN,12 C.N. Portuense,1:38.04,-
37,50m: 47.61 47.61 100m:,NaN,1:38.04 50.43,NaN,NaN
38,"19. MINAYA COELLO, Elena",NaN,12 C.D.N. Ciudad De Algeciras,1:41.69,-
39,50m: 49.69 49.69 100m:,NaN,1:41.69 52.00,NaN,NaN
40,"20. PRIAN PEREZ, Paula",NaN,12 Club Natacion Jerez,1:43.00,-
41,50m: 50.29 50.29 100m:,NaN,1:43.00 52.71,NaN,NaN
42,"21. RABINOWITZ, Emanuelle",NaN,12 C.N. Los Barrios,1:43.11,-
43,50m: 50.73 50.73 100m:,NaN,1:43.11 52.38,NaN,NaN
44,"22. ROMAN DE RUEDA, Elena",NaN,12 Club Natacion Jerez,1:46.36,-
45,1a ETAPA CIRCUITO JJNN - CÁDIZ,NaN,NaN,NaN,NaN
46,"PUERTO STA.Ma, 4/11/2023",NaN,NaN,NaN,NaN
47,"Prueba 39, Fem., 100m Espalda, Alevín Fem.",NaN,NaN,NaN,NaN
48,Clasificación AN,Tiempo,Puntos,NaN,NaN
49,"23. BOZA BAEZ, Daniela 12 C.N. Los Barrios",1:48.52,-,NaN,NaN
50,50m: 52.75 52.75 100m: 1:48.52 55.77,NaN,NaN,NaN,NaN
51,"24. LAMAS RUIZ, Claudia 12 C.N. San Fernando",1:51.42,-,NaN,NaN
52,50m: 52.08 52.08 100m: 1:51.42 59.34,NaN,NaN,NaN,NaN
53,"25. VERA ROMERO, Alicia 12 C.D.N. Sanlucar",1:52.87,-,NaN,NaN
54,50m: 54.97 54.97 100m: 1:52.87 57.90,NaN,NaN,NaN,NaN
55,"26. MELGUIZO SÁNCHEZ, África 12 C.N. Portuense",2:00.04,-,NaN,NaN
56,50m: 57.08 57.08 100m: 2:00.04 1:02.96,NaN,NaN,NaN,NaN
57,"27. MARTINEZ DE PINILLOS GONZALEZ, Ir1e2ne C.N...",2:02.67,-,NaN,NaN
58,50m: 57.92 57.92 100m: 2:02.67 1:04.75,NaN,NaN,NaN,NaN
59,"28. BELLIDO LEON, Marina 11 C.N. San Fernando",2:05.34,-,NaN,NaN

In [7]:
ResultList_25 = "ptabus/ResultList_25.ptabu"
ResultList_26 = "ptabus/ResultList_26.ptabu"
ResultList_27 = "pdfs/ResultList_27.pdf"

In [12]:
tabu25 = tabula.read_pdf(ResultList_25, pages='all')
tabu25 = tabu25[0]
tabu26 = tabula.read_pdf(ResultList_26, pages='all')
tabu26 = tabu26[0]
tabu27 = tabula.read_pdf(ResultList_27, pages='all')
tabu27 = tabu27[0]
print(tabu25.head(5))
print(tabu25.columns)
print(tabu26.head(5))
print(tabu26.columns)

                     Prueba 25                Masc., 200m Estilos Unnamed: 0  \
0           04/11/2023 - 16:15                                NaN        NaN
1                Clasificación                                 AN        NaN
2  1. RODRIGUEZ CASTRO, Victor      11 C.D.N. Ciudad De Algeciras        NaN
3       50m: 36.09 36.09 100m:  1:16.40 40.31 150m: 2:04.16 47.76      200m:
4      2. MOLINA NUÑEZ, Victor               11 C.N. San Fernando        NaN

  Unnamed: 1 Alevín Masc.
0        NaN   Resultados
1     Tiempo       Puntos
2    2:41.21            -
3    2:41.21        37.05
4    2:58.52            -
Index(['Prueba 25', 'Masc., 200m Estilos', 'Unnamed: 0', 'Unnamed: 1',
       'Alevín Masc.'],
      dtype='object')
                   Prueba 26                 Fem., 200m Estilos  Unnamed: 0  \
0         04/11/2023 - 16:20                                NaN         NaN
1              Clasificación                                 AN         NaN
2  1. ESCOBAR CHERBUY, Clara                11 C.N. Los Barrios         NaN
3     50m: 32.25 32.25 100m:  1:09.95 37.70 150m: 1:58.47 48.52         NaN
4    2. MENA OROZCO, Carlota                 11 C.D.N. Sanlucar         NaN

  Unnamed: 1 Unnamed: 2 Alevín Fem.
0        NaN        NaN  Resultados
1        NaN     Tiempo      Puntos
2        NaN    2:36.46           -
3      200m:    2:36.46       37.99
4        NaN    2:40.31           -
Index(['Prueba 26', 'Fem., 200m Estilos', 'Unnamed: 0', 'Unnamed: 1',
       'Unnamed: 2', 'Alevín Fem.'],
      dtype='object')

In [26]:
print(tabu27.head(10))
print(tabu27.columns)

                                  Prueba 27 Masc., 100m Libre  \
0                        04/11/2023 - 16:28               NaN
1                             Clasificación                AN
2                   1. VERDEJO JAÉN, Javier                14
3                    50m: 44.53 44.53 100m:           1:34.73
4  2. RODRIGUEZ GARCIA DE DIONISIO, Ma1r4io               NaN
5                    50m: 45.87 45.87 100m:           1:36.65
6                  3. REAL DELGADO, gonzalo                14
7                    50m: 44.90 44.90 100m:           1:36.92
8            4. PALMERO ESPINOSA, Alejandro                14
9                    50m: 44.86 44.86 100m:           1:37.96

                       Unnamed: 0 Unnamed: 1 Benjamin 2014.
0                             NaN        NaN     Resultados
1                             NaN     Tiempo         Puntos
2                C.N. Los Barrios    1:34.73              -
3                           50.20        NaN            NaN
4               C.N. San Fernando    1:36.65              -
5                           50.78        NaN            NaN
6             Club Natacion Jerez    1:36.92              -
7                           52.02        NaN            NaN
8  Club Deportivo Waterpolo Jerez    1:37.96              -
9                           53.10        NaN            NaN
Index(['Prueba 27', 'Masc., 100m Libre', 'Unnamed: 0', 'Unnamed: 1',
       'Benjamin 2014.'],
      dtype='object')

In [25]:
def column_hyphens(df):
"""
df: dataframe
Output: column with more than 50% of hyphens
We use this function in points function, in order to find the column we'll called score
"""
for column in df.columns:
hyphen_count = sum(df[column] == "-")
if hyphen_count >= len(df) / 4:
return column

return hyphen_count

print(tabu27.columns)

Index(['Prueba 27', 'Masc., 100m Libre', 'Unnamed: 0', 'Unnamed: 1',
       'Benjamin 2014.'],
      dtype='object')

# List of Teams Webscrapping

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.webdriver.support.wait import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC

In [2]:
driver = webdriver.Firefox()  # Initialize your WebDriver

driver.get("https://rfen.es/es/clubs")

Empty df

In [3]:
df = pd.DataFrame({'comunidad_autonoma': [], 'provincia': [], 'clubes': []})

In [ ]:
driver.find_elements(By.CLASS_NAME, 'colstyle-delegacion')

In [1]:
import functions200m as fun200
import pandas as pd
import tabula
import csv

In [2]:
pdf = "pdfs/ResultList_25.pdf"
tabu = tabula.read_pdf(pdf, pages='all')
tabu = tabu[0]
gender, distance, style, category, date, time = fun200.gender_distance_style_category_date_time(tabu)
tabu = fun200.add_columns(tabu, gender=gender, distance=distance, style=style, category=category, date_string=date, time_string=time) #add_columns has dataframe as input
tabu = fun200.nas_rows(tabu)
# reset index of tabu
tabu.reset_index(drop=True, inplace=True)
# tabu = delete_columns(tabu) 
tabu = fun200.evenANDpuntos(tabu)

In [3]:
print(tabu.head(5))

                      Prueba 25            Masc., 200m Estilos Unnamed: 1  \
0   1. RODRIGUEZ CASTRO, Victor  11 C.D.N. Ciudad De Algeciras    2:41.21
1       2. MOLINA NUÑEZ, Victor           11 C.N. San Fernando    2:58.52
2  3. RODRIGUEZ PIÑERO, Antonio           11 C.N. San Fernando    2:58.53
3         4. VIRUES ALBA, Pablo           11 C.N. San Fernando    3:09.83
4      5. RAMBOUK LARRUD, Imran  12 C.D.N. Ciudad De Algeciras    3:19.27

  Alevín Masc. gender distance    style category       date      time
0            -   masc      200  estilos   alevin 2023-11-04  16:15:00
1            -   masc      200  estilos   alevin 2023-11-04  16:15:00
2            -   masc      200  estilos   alevin 2023-11-04  16:15:00
3            -   masc      200  estilos   alevin 2023-11-04  16:15:00
4            -   masc      200  estilos   alevin 2023-11-04  16:15:00

In [4]:
df = tabu.copy()
df.iloc[:,0] = df.iloc[:,0].str.split('.')
# df[['first_surname', 'second_surname', 'name']] = df.iloc[:,0].str.split(' ', 2, expand=True)
# remove the first column
first_column = df.columns[0]
df[["drop", "full_name"]] = pd.DataFrame(df[first_column].tolist(), index= df.index)
df.drop(first_column, axis=1, inplace=True)
df.drop("drop", axis=1, inplace=True)
# Reset index
df.reset_index(drop=True, inplace=True)

# remove , in full_name
df["full_name"] = df["full_name"].str.replace(',', '')
# split full_name in three columns: firstname, secondname and name
name_parts = df['full_name'].str.split()

df['first_surname'] = name_parts.str[0]
df['first_surname'] = df['first_surname'].str.lower()
df['second_surname'] = name_parts.str[1]
df['second_surname'] = df['second_surname'].str.lower()
df['name'] = name_parts.str[2]
df['name'] = df['name'].str.lower()
# remove full_name
df.drop("full_name", axis=1, inplace=True)

# first surname first column second surname second column and name third column
cols = df.columns.tolist()
cols = cols[-3:] + cols[:-3]
df = df[cols]

# reset index
df.reset_index(drop=True, inplace=True)

# drop column 5
df.drop(df.columns[5], axis=1, inplace=True)

# reset index
df.reset_index(drop=True, inplace=True)

In [37]:
# Teams
file = open("clubs.csv", "r")
# dataframe from csv file with header
teams_rfen = pd.DataFrame(csv.reader(file, delimiter=","))
# make first row as header
teams_rfen.columns = teams_rfen.iloc[0]
# remove first row
teams_rfen = teams_rfen.iloc[1:]
# reset index
teams_rfen.reset_index(drop=True, inplace=True)
print(teams_rfen["clubes"].tolist())
teams_column_name = fun200.find_teams(df, teams_rfen["clubes"].tolist())
columns = df.columns.tolist()

for column in columns:
for element in df[column].tolist():
if type(element) == str:
element = fun200.make_lowercase(element)
element = fun200.remove_accents(element)
element = fun200.remove_whitespace(element)
for character in element:
if character.isdigit():
element = element.replace(character, '')
if element in teams_rfen["clubes"].tolist():
print(column)

['a.c.almassera', 'a.c.d.entretorres', 'a.c.e.j.lajunquera', 'a.c.r.emp', 'a.campurriananatacion', 'a.cantabranat.', 'a.d.a.calatayud', 'a.d.alberdiproinca', 'a.d.aljarafexxi', 'a.d.arjona', 'a.c.almassera', 'a.c.d.entretorres', 'a.c.e.j.lajunquera', 'a.c.r.emp', 'a.campurriananatacion', 'a.cantabranat.', 'a.d.a.calatayud', 'a.d.alberdiproinca', 'a.d.aljarafexxi', 'a.d.arjona', 'a.d.atlantida', 'a.d.bierzoalto', 'a.d.c.lasmatas', 'a.d.c.nara', 'a.d.castalla', 'a.d.d.y.a.', 'a.d.fogar', 'a.d.guacamayo', 'a.d.inefgalicia', 'a.d.manuelllaneza', 'a.d.marmenor', 'a.d.municipalyecla', 'a.d.n.caceres', 'a.d.n.mairenadelalcor', 'a.d.n.maristas', 'a.d.n.mostoles', 'a.d.naut.denaron', 'a.d.nazarenaplat.', 'a.d.neptunozamora', 'a.d.perpetuosocorro', 'a.d.plasencia96', 'a.d.ramonycajal', 'a.d.rivasnatacion', 'a.d.santacruz', 'a.d.sarria', 'a.d.sincroretiro', 'a.d.tensalus', 'a.d.triatlonoleiros', 'a.d.triatlonpacense', 'a.d.u.n.a.', 'a.d.waterpolosantoña', 'a.d.waterpolozaragoza', 'a.d.zoiti89', 'a.e.f.d.shotokan', 'a.e.n.jupitersantmarti', 'a.e.noubarris', 'a.e.santaeulalia', 'a.e.sincromataro', 'a.e.trinitatvella', 'a.helmanticanat.', 'a.masterbaleares', 'a.mirandesadenat.', 'a.n.andaluza2004', 'a.n.gramenet', 'a.p.martos', 'a.padresyamigos', 'a.r.concepcionciudadlineal', 'a.r.losalcores', 'abadiñokoastolai.k.t.', 'acquasincroartisticaelpuig', 'ad.barriovictoria', 'ad.n.bahiasantander', 'ad.puertosta.maria', 'ae.n.xtothomlleida', 'agr.e.cancaralleu', 'aironc.', 'alava', 'albaida', 'almacellesn.c.', 'aloñamendik.e.', 'amigosriadenavia', 'amorebieta-etxano', 'amorebieta-etxanowaterpolo', 'aquatichortanord', 'aragonmasterc.d.', 'ardoic.n.i.k.', 'arenass.d.', 'asoc.dep.debase', 'asoc.vet.guipuzcoa', 'asociaciondeportivaacuatica', 'associacioesportivasincrovalfago', 'asturn.c.', 'ateneusantboia', 'atleticosansebastian', 'atleticotomellosonatacion', 'atxondoi.k.t.', 'b.atneumontserrat', 'bahiadealmerian.c', 'barduliai.k.t.', 'besaluc.n.', 'bestmediterranean', 'bilbaoaingeruakigeriketakluba', 'bisairesc.n.', 'bizkaia', 'buruntzaldeaikt', 'c..d.tiburonblanco', 'c.a.a.alone', 'c.a.baixmaestrat', 'c.a.n.d.oleiros', 'c.a.n.illadebenidorm', 'c.a.s.colomo-olimpo', 'c.a.sansebastian', 'c.a.torresdesegre', 'c.acuaticoalbacete', 'c.acuaticosalamanca', 'c.ademan', 'c.aiguaesportarta', 'c.al-basit', 'c.alamedadeosuna', 'c.amistatdeserveissocials,esportiusialajoventut', 'c.angles-farnes"laselva"', 'c.aquaticcastello', 'c.aquaticdealicante', 'c.aquaticoavilessolras', 'c.aquaticxaloc', 'c.arkitze', 'c.askartza', 'c.asland', 'c.asoc.coruñesadewat.', 'c.asturianooviedo', 'c.atleticoarteixo', 'c.atleticonadir', 'c.atletismohuesca', 'c.b.bosco', 'c.b.dominicasvistabella', 'c.b.rebote', 'c.b.torredelmar', 'c.b.vicentetofiño', 'c.b.villanuevadelacañada', 'c.balonmanocoria', 'c.c.delosejercitos', 'c.c.s.bilbaina', 'c.calasanz', 'c.caminosdegranada', 'c.campodeferrol', 'c.campodejaen', 'c.cartuja', 'c.ceman', 'c.cincovillas', 'c.costacalida', 'c.costatropical', 'c.d.a.d.zamora', 'c.d.albaceteswim', 'c.d.alcarreñodes.', 'c.d.alfa-5', 'c.d.amaya', 'c.d.aquadevaldepeñas', 'c.d.aquasalvamento', 'c.d.aquaslava', 'c.d.aquatierra', 'c.d.arete', 'c.d.atenea', 'c.d.aznalcazar', 'c.d.b.villaviciosadeodon', 'c.d.belenmaria', 'c.d.berceo', 'c.d.bilbao', 'c.d.casadevenezuelaencanarias', 'c.d.clarin', 'c.d.colegioelvalle', 'c.d.delfineshellin', 'c.d.denatacionerese', 'c.d.e.calipso', 'c.d.e.mako', 'c.d.e.malvar', 'c.d.e.natacionchiboi', 'c.d.e.polid.quijote', 'c.d.e.sierradeguadarrama', 'c.d.elgiraldillo', 'c.d.elvalle', 'c.d.enriquesoler', 'c.d.epsilonsevilla', 'c.d.escuelanadadorestomelloso', 'c.d.espartaalcorcon', 'c.d.espartinas', 'c.d.fortuna', 'c.d.futsi', 'c.d.gines', 'c.d.granadanatacionmaster', 'c.d.granvia-mar', 'c.d.gredossandiego', 'c.d.h2o', 'c.d.halegatos', 'c.d.herbania', 'c.d.hydra', 'c.d.inacuaantonioprieto', 'c.d.indea', 'c.d.izarra,i.c.', 'c.d.jereznatacionmaster', 'c.d.jescagua', 'c.d.lamolinera', 'c.d.lasarte-oria', 'c.d.lledo', 'c.d.losalamosmotril', 'c.d.m.guadalajara', 'c.d.m.sanfernando', 'c.d.masterhuelva', 'c.d.mastertartessos', 'c.d.mistral', 'c.d.moia', 'c.d.monovar', 'c.d.multideportesoviedo', 'c.d.n.arahal', 'c.d.n.bajalarga', 'c.d.n.bentacu-laguna', 'c.d.n.bidasoaxxi', 'c.d.n.cazalla', 'c.d.n.chiclana', 'c.d.n.ciudaddesantiago', 'c.d.n.cordoba', 'c.d.n.inacuamalaga', 'c.d.n.macael', 'c.d.n.masterlosalcores', 'c.d.n.mastervalladolid', 'c.d.n.meatzaldeadeabantoyzierbena', 'c.d.n.nadamaslasmarinas', 'c.d.n.palmadelrio', 'c.d.n.puertodelatorre', 'c.d.n.sanandres', 'c.d.n.sanjoseobrero', 'c.d.n.sanlucar', 'c.d.n.schamann', 'c.d.n.sincronizadaalgeciras', 'c.d.n.sincronizadasestao', 'c.d.n.torrejon', 'c.d.n.urpolozaleakdedonostia', 'c.d.n.valparaisodegranada', 'c.d.n.zamora', 'c.d.natacion79', 'c.d.natacionandujar', 'c.d.natacionboadilla', 'c.d.natacioncalle4', 'c.d.natacioncastulo', 'c.d.natacionmaster', 'c.d.natacionmedinense', 'c.d.natacionneptunya', 'c.d.noain', 'c.d.nonadamos', 'c.d.novaschool', 'c.d.olimpicjativa', 'c.d.paraiso', 'c.d.parquesol', 'c.d.pedromenendez', 'c.d.piratasteruel', 'c.d.portosol', 'c.d.poseidon', 'c.d.quabeartistica', 'c.d.resist4', 'c.d.rotatiburones', 'c.d.s.e.k.', 'c.d.sadus', 'c.d.sakanaigeriketataldea', 'c.d.salvamentonatacionsilla', 'c.d.santaana', 'c.d.santjoan', 'c.d.sek', 'c.d.siero-deporte', 'c.d.sincrobarbastro', 'c.d.sincrograncamar', 'c.d.sincroibiza', 'c.d.stadioalicante', 'c.d.swimgranada', 'c.d.talamanca', 'c.d.teamevasionrunning', 'c.d.tizonaburgos', 'c.d.torrelagowellness', 'c.d.trampolin', 'c.d.trecus', 'c.d.triatlonalhaurindelatorre', 'c.d.turaniana', 'c.d.univ.demalaga', 'c.d.universidaddealmeria', 'c.d.universidaddesantiago', 'c.d.universitario', 'c.d.utreraacuatica', 'c.d.vand´03', 'c.d.villadepravia', 'c.d.virgendereyes', 'c.d.waterpoloiruña9802', 'c.d.waterpolomalaga', 'c.d.waterpolonavarra', 'c.d.waterpoloturia', 'c.dehielobenalmadena', 'c.dep.patosverdes', 'c.deportivoalquimia', 'c.deportivoipponraulcalvo', 'c.derecho(waterpolo)', 'c.detiromosqueteros', 'c.drink', 'c.dtriatlonlacerta', 'c.dwaterpolosanlucar', 'c.e.bellvis', 'c.e.bucaner', 'c.e.dinamicsamposta', 'c.e.eldense', 'c.e.guardiaurbanadebarcelona', 'c.e.inefdelleida', 'c.e.latosca', 'c.e.mediterrani', 'c.e.n.balaguer', 'c.e.n.cabrerademar', 'c.e.n.casal', 'c.e.palauplegamans', 'c.e.panteresgrogues', 'c.e.picornell', 'c.e.sincroinca', 'c.e.vendrell', 'c.elcandado', 'c.elcorzo', 'c.elpicacho', 'c.encinasdeboadilla', 'c.escolapiossarria', 'c.escuderiaalba', 'c.escuelan.langreo', 'c.espartal', 'c.esportsmasters', "c.esquivalld'aran", 'c.evicdeporte', 'c.figueroa', 'c.fluvialdelugo', 'c.fregenalsierra', 'c.fuentedelrey', 'c.galaicosincro', 'c.gimnasticomedico', 'c.golflosvillares', 'c.hispanico', 'c.huarte', 'c.igeriketalaudio', 'c.ignaciosafa', 'c.ins.dep.iberdrola', 'c.item', 'c.kai-eder(nat.)', 'c.landatxueta', 'c.lomamargaritas', 'c.lospatos', 'c.m.i.clubdecampo', 'c.m.melilla', 'c.m.n.arganda', 'c.marinedas.d.', 'c.martiartu', 'c.marvillagarcia', 'c.mediosacuaticos', 'c.mediterranea', 'c.mediterranisincro', 'c.mejorasdelvalle', 'c.militardeportivo', 'c.mirasan', 'c.n.a.pueblonuevo', 'c.n.abulense', 'c.n.ademar', 'c.n.aguacan', 'c.n.aguilas', 'c.n.aguimayro', 'c.n.alarcosciudadreal', 'c.n.albacete', 'c.n.albacora', 'c.n.albatros', 'c.n.alcala', 'c.n.alcalah', 'c.n.alcanar', 'c.n.alcantarilla', 'c.n.alcazar', 'c.n.alcobendas', 'c.n.alcoi', 'c.n.alcoyano', 'c.n.alfailicitano', 'c.n.alhama', 'c.n.alhambra', 'c.n.alhaurinelgrande', 'c.n.almansa', 'c.n.almenar', 'c.n.almendralejo', 'c.n.almeria', 'c.n.alora', 'c.n.altoaragon', 'c.n.amposta', 'c.n.amurrio', 'c.n.andaraz', 'c.n.andratx', 'c.n.antartida', 'c.n.aquamasters', 'c.n.aquaticfuelsportvalencia', 'c.n.aranjuez', 'c.n.armilla', 'c.n.arnedo', 'c.n.arrasate', 'c.n.arteixo', 'c.n.artes', 'c.n.artesadesegre', 'c.n.artisticaatlantis', 'c.n.artisticapswaterbenidorm', 'c.n.arzua', 'c.n.aspe', 'c.n.aspontes', 'c.n.astillero', 'c.n.astur-union', 'c.n.asturovi', 'c.n.atlanta', 'c.n.atletic-barceloneta', 'c.n.aviles', 'c.n.avinyo', 'c.n.axarquia', 'c.n.azaharsincro', 'c.n.azaharvila-real', 'c.n.azuer', 'c.n.badajoz', 'c.n.badalona', 'c.n.badia', 'c.n.bahiadecadiz', 'c.n.bahiaostende', 'c.n.baixomiño', 'c.n.balsereny', 'c.n.banyoles', 'c.n.barakaldo', 'c.n.barcelona', 'c.n.basauri', 'c.n.begastri', 'c.n.bellavista', 'c.n.benicarlo', 'c.n.benidorm', 'c.n.benifayo', 'c.n.benissa', 'c.n.bergara', 'c.n.betera', 'c.n.bierzo-ponferrada', 'c.n.blanes', 'c.n.boiro', 'c.n.bormujos', 'c.n.buceociudaddehellin', 'c.n.burgos', 'c.n.burlada', 'c.n.butsenit', 'c.n.c.frusol', 'c.n.caballa', 'c.n.caballa-ciudaddeceuta', 'c.n.caceres', 'c.n.cadiz', 'c.n.caldes', 'c.n.calella', 'c.n.calpe', 'c.n.calvia', 'c.n.camargo', 'c.n.camas', 'c.n.campdemorvedre', 'c.n.campoamor', 'c.n.capellades', 'c.n.cardedeuantic', 'c.n.carmona', 'c.n.cartagonovacartagena', 'c.n.carucagua', 'c.n.castellet', 'c.n.castellfollit', 'c.n.castilla', 'c.n.castilla-burgos', 'c.n.castillazamora', 'c.n.catalunya', 'c.n.catarroja', 'c.n.cedeira', 'c.n.centelles', 'c.n.cerceda', 'c.n.cerdanyola', 'c.n.cerradocalderon', 'c.n.cervera', 'c.n.chafarinas(r.52)', 'c.n.chinato', 'c.n.chinchilla', 'c.n.chiva', 'c.n.chofaracay', 'c.n.churriana', 'c.n.ciudadalta', 'c.n.ciudaddealcorcon', 'c.n.ciudaddegijon', 'c.n.ciudaddemurcia', 'c.n.ciudaddeoviedo', 'c.n.ciudadmallorca', 'c.n.ciudadreal', 'c.n.ciutadella', 'c.n.ciutatdepalma', 'c.n.colegiomirasur', 'c.n.colmenarviejo', 'c.n.comarcaguadalhorce', 'c.n.compostela', 'c.n.conil', 'c.n.corazonistas', 'c.n.coria', 'c.n.cornella', 'c.n.coruña', 'c.n.coslada', 'c.n.criptanagigantes', 'c.n.cuatrocaminos', 'c.n.cuenca', 'c.n.culleredo', 'c.n.delfin', 'c.n.delfinesdeocaña', 'c.n.delsegura', 'c.n.denia', 'c.n.doñamencia', 'c.n.donbenitoacuarun', 'c.n.donbosco', 'c.n.doncel', 'c.n.doshermanas', 'c.n.e.gandia', 'c.n.easo', 'c.n.easwinartisticaanoeta21', 'c.n.echeyde', 'c.n.eivissa', 'c.n.elcarpio', 'c.n.elche', 'c.n.elcisne', 'c.n.elmasnou', 'c.n.elpapiol', 'c.n.esalvamentoaestrada', 'c.n.escualos', 'c.n.esplugues', 'c.n.fanaticswimcastellon', 'c.n.felanitx', 'c.n.fenixmanises', 'c.n.ferca-sanjose', 'c.n.ferrol', 'c.n.figueres', 'c.n.fuengirola', 'c.n.fuengirola', 'c.n.fuenlabrada', 'c.n.fuentealamo', 'c.n.galaico', 'c.n.gava', 'c.n.gernika', 'c.n.gimenells', 'c.n.gimn.raspall', 'c.n.gimn.valladolid', 'c.n.gines', 'c.n.grado', 'c.n.granadaogijares', 'c.n.grañen', 'c.n.granollers', 'c.n.haliavila-real', 'c.n.heliomar', 'c.n.helios', 'c.n.herencia', 'c.n.horadada', 'c.n.huelva', 'c.n.igarondo', 'c.n.igualada', 'c.n.imd-ciudaddesegovia', 'c.n.inca', 'c.n.indaes', 'c.n.indaloalmeria', 'c.n.instituodeportivomonovar', 'c.n.instituto-queipo', 'c.n.iregua-villamediana', 'c.n.isoraswimguaju', 'c.n.izarraitz', 'c.n.izcuarte', 'c.n.j-10', 'c.n.jaen', 'c.n.jaen99', 'c.n.jamma', 'c.n.jimenez', 'c.n.jotaeme', 'c.n.judizmendi', 'c.n.kallipolis', 'c.n.laalameda', 'c.n.lacarolina', 'c.n.laceta', 'c.n.lacolina', 'c.n.lacostera', 'c.n.lalatina', 'c.n.lalin', 'c.n.lamarina', 'c.n.lapaz', 'c.n.lares', 'c.n.larinconada', 'c.n.lasalle-melilla', 'c.n.lasalle-palma', 'c.n.lasanclascastrillon', 'c.n.lasescuevas', 'c.n.lasnorias', 'c.n.laspalmas', 'c.n.lavalld´uixo', 'c.n.lavallmond´aigua', 'c.n.leganes', 'c.n.legazpi', 'c.n.leon', 'c.n.lepe', 'c.n.lescomadres', 'c.n.liceo', 'c.n.linares', 'c.n.linense', 'c.n.lleida', 'c.n.lliria', 'c.n.lloret-canyelles', 'c.n.lloretdemar', 'c.n.llucmajor', 'c.n.logroño', 'c.n.lorca', 'c.n.losangeles', 'c.n.losbarrios', 'c.n.loscristianos', 'c.n.lospalacios', 'c.n.lostimones', 'c.n.luarca', 'c.n.lucena', 'c.n.lugo', 'c.n.lugones', 'c.n.luisasensi', 'c.n.l´alcudia', 'c.n.l´hospitalet', 'c.n.m.jaca', 'c.n.madridejos', 'c.n.madridmoscardo', 'c.n.maimona', 'c.n.mairenaaljarafe', 'c.n.malgratdemar', 'c.n.manresa', 'c.n.manzanares', 'c.n.mao', 'c.n.marbella', 'c.n.marbellacarabanchel', 'c.n.marenostrum', 'c.n.marina-cartagena"ancora"', 'c.n.marmenorsanjavier', 'c.n.martorell', 'c.n.masella', 'c.n.maspalomas', 'c.n.mastercordoba', 'c.n.masterjaen', 'c.n.mastermadrid', 'c.n.mastermos', 'c.n.mastermurcia', 'c.n.masternaturalswimpetrer', 'c.n.mastersa.crol', 'c.n.mataro', 'c.n.mediocudeyo', 'c.n.mediterraneovalencia', 'c.n.mejorada2007', 'c.n.menditxo', 'c.n.merida', 'c.n.metropole', 'c.n.metropolitan', 'c.n.mijas', 'c.n.mirasierra', 'c.n.molina', 'c.n.molinsderei', 'c.n.moncada', 'c.n.monteverde', 'c.n.montilla', 'c.n.montjuic', 'c.n.montoro', 'c.n.moralo', 'c.n.morelia', 'c.n.mos', 'c.n.murciasanjorge', 'c.n.nassica', 'c.n.navarcles', 'c.n.navas', 'c.n.nazari', 'c.n.neptuno', 'c.n.neptuno-l´alcudia', 'c.n.neptunoalbacete', 'c.n.neptunodepozoblanco', 'c.n.noia', 'c.n.novelda', 'c.n.o.lagarriga', 'c.n.ocaña', 'c.n.olimpia', 'c.n.olimpiada', 'c.n.olivenza', 'c.n.olot', 'c.n.olympicdombosconazaret', 'c.n.onda', 'c.n.ondina', 'c.n.ontinar', 'c.n.ontinyent', 'c.n.ortigueira', 'c.n.ovimaster', 'c.n.pabellonourense', 'c.n.padron', 'c.n.palamos', 'c.n.palau', 'c.n.palencia', 'c.n.palos', 'c.n.pamplona', 'c.n.parets', 'c.n.peleño', 'c.n.petrer', 'c.n.picassent', 'c.n.pilarhoradada', 'c.n.piscinalanuciacamilocano', 'c.n.piscis-mislata', 'c.n.pistario', 'c.n.palos', 'c.n.pamplona', 'c.n.parets', 'c.n.peleño', 'c.n.petrer', 'c.n.picassent', 'c.n.pilarhoradada', 'c.n.piscinalanuciacamilocano', 'c.n.piscis-mislata', 'c.n.pistario', 'c.n.pizarra', 'c.n.plasencia', 'c.n.plataforma3oceano', 'c.n.playasalve', 'c.n.pobla', 'c.n.poblenou', 'c.n.ponferrada', 'c.n.poniente-vicar', 'c.n.ponteareas', 'c.n.pontevedra', 'c.n.portamiñalugo', 'c.n.portocarrero', 'c.n.portuense', 'c.n.portus', 'c.n.pozoblanco', 'c.n.pozuelo', 'c.n.pratllobregat', 'c.n.premia', 'c.n.proserpina', 'c.n.puertollano', 'c.n.puertolumbreras', 'c.n.puertoreal', 'c.n.quartdepoblet', 'c.n.quinaqua', 'c.n.quintanar', 'c.n.ra', 'c.n.rana', 'c.n.raspeig', 'c.n.reales', 'c.n.redondela', 'c.n.reusploms', 'c.n.riasbaixas', 'c.n.riavall', 'c.n.riba-roja', 'c.n.riembaup.d´aro', 'c.n.ripollet', 'c.n.riudevitlles', 'c.n.riveira', 'c.n.riviera', 'c.n.romil', 'c.n.reusploms', 'c.n.riasbaixas', 'c.n.riavall', 'c.n.riba-roja', 'c.n.riembaup.d´aro', 'c.n.ripollet', 'c.n.riudevitlles', 'c.n.riveira', 'c.n.riviera', 'c.n.romil', 'c.n.roquetas', 'c.n.rubi', 'c.n.rute', 'c.n.s.fabionelli', 'c.n.s.oriolimperial', 'c.n.sabadell', 'c.n.sabiñanigo', 'c.n.saguntomorvedremaster', 'c.n.salamanca', 'c.n.sallent', 'c.n.salnes', 'c.n.salou', 'c.n.salv.nuevasavia', 'c.n.salvamentoysocorrismoconsuegra', 'c.n.samaruc', 'c.n.sanblas', 'c.n.sancarlos', 'c.n.sanfernando', 'c.n.sanfernando', 'c.n.sanfernandodehenares', 'c.n.sanfost', 'c.n.sangenjo', 'c.n.sangregorio', 'c.n.sanjaviermarmenor', 'c.n.sanjuan', 'c.n.sanlorenzodeelescorial', 'c.n.sanmartin', 'c.n.sanmartindelreyaurelio', 'c.n.sanroque', 'c.n.sanroque', 'c.n.santabarbara', 'c.n.santadria', 'c.n.santander', 'c.n.santandreu', 'c.n.santantontremp', 'c.n.santaolaya', 'c.n.santaperpetua', 'c.n.santboi', 'c.n.santfeliu', 'c.n.santfruitos', 'c.n.santiago', 'c.n.santoreino', 'c.n.santpedor', 'c.n.santsadurni', 'c.n.santurtzi', 'c.n.sanvicente', 'c.n.sanxenxo', 'c.n.sevilla', 'c.n.sierranevada', 'c.n.sierraoeste', 'c.n.sierrasur', 'c.n.sinc.montrove', 'c.n.sincroastur', 'c.n.sincronizadaalbacete', 'c.n.sincronizadacostablanca', 'c.n.sincronizadamorvedresagunto', 'c.n.sincronizadaourense', 'c.n.sincronizadaphoenix', 'c.n.sincronizadapontevedra', 'c.n.sincronizadariasbaixasvigo', 'c.n.sincrosevilla', 'c.n.sincroviedo', 'c.n.sitges', 'c.n.soriano', 'c.n.spartansharks', 'c.n.sta.eulaliario', 'c.n.sueca', 'c.n.tabira', 'c.n.tarifa', 'c.n.tarraco', 'c.n.tarrega', 'c.n.teneteide', 'c.n.teniselche', 'c.n.tercio', 'c.n.terrassa', 'c.n.teruel', 'c.n.toledo', 'c.n.tomelloso', 'c.n.tormes', 'c.n.tornabous', 'c.n.torrelavega', 'c.n.torremolinos', 'c.n.torrevieja', 'c.n.torrijos', 'c.n.tortosa', 'c.n.tossal-alicante', 'c.n.tramuntana', 'c.n.trencaonesalzira', 'c.n.trescantos', 'c.n.tritonbierzo', 'c.n.trujillo', 'c.n.turis', 'c.n.ubrique', 'c.n.umia', 'c.n.unionrinconada', 'c.n.urgain', 'c.n.urta', 'c.n.utiel', 'c.n.utrera', 'c.n.v.elrefugio', 'c.n.valdepeñas', 'c.n.valenciamasterssedavi', 'c.n.valledearanguren', 'c.n.valledelkas', 'c.n.vallenalon', 'c.n.valleverde', 'c.n.vallirana', 'c.n.vallmont', 'c.n.vendrell', 'c.n.vic-etb', 'c.n.vigo', 'c.n.vila-real', 'c.n.vila-seca', 'c.n.viladecans', 'c.n.vilafranca', 'c.n.vilanova', 'c.n.villadeagüimes20cnva16', 'c.n.villadenavia', 'c.n.villadetorrepacheco', 'c.n.villafrancac.', 'c.n.villalba', 'c.n.villanuevadelacañada', 'c.n.villarrense', 'c.n.villarrobledo', 'c.n.villenaaltovinalopo', 'c.n.vinaros', 'c.n.voltorbalear', 'c.n.vulcaniamaster', 'c.n.w.diverswin', 'c.n.w.majadahonda', 'c.n.xativa', 'c.n.xirivella', 'c.n.xove', 'c.n.xuquer', 'c.n.yecla', 'c.n.zadorra', 'c.n.zafra', 'c.n.zamora', 'c.n.zaragoza89', 'c.n.zaragozacentro', 'c.n.zubi-aurre', 'c.n.zuera', 'c.natacion81', 'c.nauticodelaredo', 'c.nauticoestartit', 'c.nauticogradense', 'c.nauticomirandes', 'c.nauticosevilla', 'c.nauticotarragona', 'c.navalpontevedra', 'c.nazaret', 'c.neptunodecordoba', 'c.npiera2012', 'c.o.farners', 'c.olivalafrontera', 'c.p.a.a.mairenaaljarafe', 'c.p.albaceten.', 'c.p.alcaudete', 'c.p.beasdesegura', 'c.p.bullas', 'c.nazaret', 'c.neptunodecordoba', 'c.npiera2012', 'c.o.farners', 'c.olivalafrontera', 'c.p.a.a.mairenaaljarafe', 'c.p.albaceten.', 'c.p.alcaudete', 'c.p.beasdesegura', 'c.p.bullas', 'c.p.c.s.somontano', 'c.p.cadiz', 'c.p.d.abadessenc', 'c.p.eltemple', 'c.p.flassa', 'c.p.fraga', 'c.p.granada74', 'c.p.huelva', 'c.p.j.calahorra', 'c.p.laroda', 'c.p.nerja', 'c.p.puigcerda', 'c.p.record', 'c.p.santamªdeguia', 'c.p.santjoanenc', 'c.p.sariñena', 'c.padelarenaalicante', "c.palaud'anglesola", 'c.pamesademotril', 'c.parayass.d.', 'c.patin-vic', 'c.peñalba', 'c.pentatlonmelilla', 'c.pescaelpuntal(probas)', 'c.pinedadesevilla', 'c.pinosdellimonar', 'c.poloacuatico', 'c.quintadelorca', 'c.ramonllull', 'c.ripolle.s.', 'c.s.d´inca', 'c.s.p.losllanos', 'c.salaslarrazabal', 'c.saltosmallorca', 'c.sanestanislao', 'c.sanmarcos', 'c.santanadelinares', 'c.santuario', 'c.sincroalhama', 'c.sincroandratx', 'c.sincrolamurterachristeyns', 'c.sincrourbarrideetxebarri', 'c.sirenascatarroja', 'c.squashblanes', 'c.t.hocesdecuenca', 'c.tafalles', 'c.tenerifemasters', 'c.tenisbadalona', 'c.tenisbarcino', 'c.teniscabezarubia', 'c.tenischamartin', 'c.teniscodesal', 'c.teniscuenca', 'c.tenisjuanbravo', 'c.tenislleida', 'c.tenismurcia', 'c.tenispamplona', 'c.tenisponferrada', 'c.tenisvic', 'c.tenisvilafranca', 'c.tenisvillanueva', 'c.torrentedecinca', 'c.traviesasnat.', 'c.triatlonalbacete', 'c.triatloncoruña', 'c.u.oceano', 'c.usc', 'c.valenciano', 'c.villanuevacordoba', 'c.w.cambre', 'c.w.castello', 'c.w.coruñariasaltas', 'c.w.diverswin', 'c.w.doshermanas', 'c.w.lugo', 'c.w.p.castellae', 'c.w.poseidon', 'c.w.redondela', 'c.w.riopico', 'c.w.sanantoniodebenageber', 'c.w.santaursula', 'c.w.santiago', 'c.w.tomares', 'c.wat.pabellonourense', 'c.wat.pontevedra', 'c.waterpolo1990', 'c.waterpoloalbacete', 'c.waterpoloalgeciras', 'c.waterpolobalear', 'c.waterpolobrilan', 'c.waterpolociudadderivas', 'c.waterpolocoruña', 'c.waterpoloe.m.t.', 'c.waterpololevanteupv', 'c.waterpololospalacios', 'c.waterpolomadridejos', 'c.waterpolomarbella', 'c.waterpolomotril', 'c.waterpolopadron', 'c.waterpolopetrer', 'c.waterpolosax', 'c.waterpolosevilla', 'c.waterpolovaldepeñas', 'c.waterpolozamora', 'c.wp.burjassot', 'c.wp.eriduycurtin', 'c.wp.santadria', 'c.wp.univ.autonoma', 'c.zizur', 'cambrilsc.n.', 'campodedeporteslarraina', 'casinodelacoruña', 'cd.españolsanvcte.', 'cd.maristasalicante', 'cd.un.polit.valencia', 'cdacuaticoleon', 'cdbnatacionswimtonic', 'cdecastronat.', 'cdupstream', 'cdwpurgaratxingudi', 'cdwtrudgeonsestao', 'centurionclubtriatloncaravaca', 'circulomercantil', 'clubaqualandia', 'clubaquamadsincro', 'clubarriacensenatacion', 'clubatleticomontemar', 'clubbaloncestocazorla', 'clubbenaventenatacion', 'clubcampusesport', 'clubdeatletismotragaleguas', 'clubdelmar', 'clubdeportivobasicobis', 'clubdeportivocaima', 'clubdeportivoestrelladelmar', 'clubdeportivomidayutenerife

In [61]:
ResultList_25 = "pdfs/ResultList_25.pdf"
tabu25 = tabula.read_pdf(ResultList_25, pages='all')
print(tabu25[0].head(5))
ResultList_27 = "pdfs/ResultList_27.pdf"
tabu27 = tabula.read_pdf(ResultList_27, pages='all')
print(tabu27[0].head(5))

                     Prueba 25                Masc., 200m Estilos Unnamed: 0  \
0           04/11/2023 - 16:15                                NaN        NaN
1                Clasificación                                 AN        NaN
2  1. RODRIGUEZ CASTRO, Victor      11 C.D.N. Ciudad De Algeciras        NaN
3       50m: 36.09 36.09 100m:  1:16.40 40.31 150m: 2:04.16 47.76      200m:
4      2. MOLINA NUÑEZ, Victor               11 C.N. San Fernando        NaN

  Unnamed: 1 Alevín Masc.
0        NaN   Resultados
1     Tiempo       Puntos
2    2:41.21            -
3    2:41.21        37.05
4    2:58.52            -
                                  Prueba 27 Masc., 100m Libre  \
0                        04/11/2023 - 16:28               NaN
1                             Clasificación                AN
2                   1. VERDEJO JAÉN, Javier                14
3                    50m: 44.53 44.53 100m:           1:34.73
4  2. RODRIGUEZ GARCIA DE DIONISIO, Ma1r4io               NaN

          Unnamed: 0 Unnamed: 1 Benjamin 2014.
0                NaN        NaN     Resultados
1                NaN     Tiempo         Puntos
2   C.N. Los Barrios    1:34.73              -
3              50.20        NaN            NaN
4  C.N. San Fernando    1:36.65              -

In [62]:
tabu27 = tabu27[0]
print(tabu27)

                                   Prueba 27 Masc., 100m Libre  \
0                         04/11/2023 - 16:28               NaN
1                              Clasificación                AN
2                    1. VERDEJO JAÉN, Javier                14
3                     50m: 44.53 44.53 100m:           1:34.73
4   2. RODRIGUEZ GARCIA DE DIONISIO, Ma1r4io               NaN
5                     50m: 45.87 45.87 100m:           1:36.65
6                   3. REAL DELGADO, gonzalo                14
7                     50m: 44.90 44.90 100m:           1:36.92
8             4. PALMERO ESPINOSA, Alejandro                14
9                     50m: 44.86 44.86 100m:           1:37.96
10              5. VELAZQUEZ CARRERAS, Dario                14
11                    50m: 48.35 48.35 100m:           1:42.86
12                 6. SOUSSI BAHRAOUI, Talal                14
13                    50m: 46.76 46.76 100m:           1:42.96
14   7. RODRIGUEZ GARCIA DE DIONISIO, Jua14n               NaN

                        Unnamed: 0 Unnamed: 1 Benjamin 2014.
0                              NaN        NaN     Resultados
1                              NaN     Tiempo         Puntos
2                 C.N. Los Barrios    1:34.73              -
3                            50.20        NaN            NaN
4                C.N. San Fernando    1:36.65              -
5                            50.78        NaN            NaN
6              Club Natacion Jerez    1:36.92              -
7                            52.02        NaN            NaN
8   Club Deportivo Waterpolo Jerez    1:37.96              -
9                            53.10        NaN            NaN
10               C.N. San Fernando    1:42.86              -
11                           54.51        NaN            NaN
12      C.D.N. Ciudad De Algeciras    1:42.96              -
13                           56.20        NaN            NaN
14               C.N. San Fernando    1:56.14              -

In [50]:
tabu

AttributeError: 'list' object has no attribute 'iloc'

# Selectfun

In [3]:
import functions200m as fun200
import functions200m as fun100
import pandas as pd
import tabula
import csv
import os

In [20]:
def selectfun(pdf):
    # if any column name has the string '4 x ' then omit do nothing
    tabu = tabula.read_pdf(pdf, pages='all')
    df = tabu[0]
    names = df.columns
    if any('4 x ' in name for name in names):
        print('relevo')
    else:
        # Detect in which column the distance is
        posible_distances = ['50m', '100m', '200m', '400m']
        for distance in posible_distances:
            for name in names:
                if (distance in name):
                    distance = ''.join([i for i in distance if not i.isalpha()])
                    return distance

In [21]:
# get list of files in pdfs folder

files = os.listdir('pdfs')
for file in files:
    if (file[0:5]!='Resul'):
        pass
    else: 
        print(file + '\n')
        print(selectfun('pdfs/' + file))

ResultList_41.pdf

50
ResultList_40.pdf

100
ResultList_42.pdf

50
ResultList_43.pdf

100
ResultList_47.pdf

relevo
None
ResultList_46.pdf

50
ResultList_44.pdf

100
ResultList_45.pdf

50
ResultList_36.pdf

relevo
None
ResultList_37.pdf

100
ResultList_35.pdf

relevo
None
ResultList_34.pdf

100
ResultList_30.pdf

200
ResultList_31.pdf

200
ResultList_25.pdf

200
ResultList_33.pdf

100
ResultList_27.pdf

100
ResultList_26.pdf

200
ResultList_32.pdf

200
ResultList_28.pdf

None
ResultList_29.pdf

200
ResultList_39.pdf

100
ResultList_38.pdf

100
ResultList_48.pdf

relevo
None
ResultList_49.pdf

relevo
None